config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#start'

  get 'searches_delete_all' => 'searches#delete_all'

  resources :users, :except => [:edit, :destroy, :index, :new, :create, :show, :update, :destroy] do
    resources :posts
    resources :searches, :except => [:edit, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :results, dependent: :destroy
  has_many :searches, through: :results
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :user
  belongs_to :search
  belongs_to :post
end

app/models/search.rb
class Search < ApplicationRecord
  belongs_to :user
  has_many :results, dependent: :destroy
  has_many :posts, through: :results
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :searches
  has_many :results
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :security

  def security
    unless user_signed_in?
      flash[:alert] = "You must be logged in to access this section"
      redirect_to root_path
    end
  end

  def index

  end

  def create
    @new_post = Post.create!(post_params.merge(user_id: params[:user_id]))
    redirect_to user_posts_path(current_user)
  end

  def new
    @new_post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def show
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to user_posts_path(current_user)
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to user_posts_path(current_user)
  end

  private
  def post_params
      params.require(:post).permit(:title, :text)
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_filter :security

  def security
    unless user_signed_in?
      flash[:alert] = "You must log in to access the site"
      redirect_to root_path
    end
  end

  def index
    @searches = current_user.searches
  end

  def create
    @search = Search.create!(search_params.merge(user_id: params[:user_id]))
    @user = User.find(params[:user_id])
    terms = @search.search_terms.split(" ")
    @user.posts.each do |post|
      number = 0
      terms.each do |trm|
        if post.text.include? trm
          @text = post.text.split(" ")
          @text.each do |word|
            if word.include? trm
              number += 1
            end
          end
        end
      end
      if number != 0
        Result.create(user_id: params[:user_id], search_id: @search.id, post_id: post.id, score: number.to_f )
      end
    end
    redirect_to user_search_path(current_user, @search)
  end

  def new
    @new_search = Search.new
  end

  def edit
  end

  def show
    @search = Search.find(params[:id])
  end

  def delete_all
    current_user.searches.destroy_all
    flash[:alert] = "Don't worry, your secret is safe with us."
    redirect_to root_path
  end

  private
  def search_params
      params.require(:search).permit(:search_terms)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def start
    if current_user
      redirect_to new_user_search_path(current_user)
    end
  end

  def index
  end

  def create
  end

  def new
  end

  def edit
  end

  def show
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SmartSearch</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <% if !current_user %>
      <%= link_to "Sign up", new_user_registration_path %>
      <%= link_to "Sign in", new_user_session_path %>
    <% else %>
      <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
        <%= current_user.email %>
    <% end %> -->
  </head>

  <body>
    <header>
      <% if notice %>
        <p class="notice"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert"><%= alert %></p>
      <% end %>
      <% if !current_user %>
        <p> <%= link_to "Sign up", new_user_registration_path %> </p>
        <p> <%= link_to "Sign in", new_user_session_path %> </p>
      <% else %>
        <p> <%= link_to "Sign out", destroy_user_session_path, :method => :delete %> </p>
        <p> <%= current_user.email %> </p>
      <% end %>
    </header>
    <main>
      <div class='content-wrapper'>
        <%= yield %>
      </div>
      <aside>
        <% if current_user %>
          <ul class="nav">
            <li> <%= link_to 'New Search', new_user_search_path(current_user) %> </li>
            <li> <%= link_to 'All Searches', user_searches_path(current_user) %> </li>
            <li> <%= link_to 'New Post', new_user_post_path(current_user) %> </li>
            <li> <%= link_to 'All Posts', user_posts_path(current_user) %> </li>
          </ul>
        <% end %>
      </aside>
    </main>
    <footer>
    </footer>

  </body>
</html>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

<h1> congratulations! you created a new page with the title </h1>
<h1> <%= @new_post.title %> </h1>
<%= link_to 'New Search', new_user_search_path(current_user) %>
<%= link_to 'See all your posts', user_posts_path(current_user) %>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<p>Edit your post!</p>
<%= form_for [current_user, @post] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :text %>
  <%= f.text_field :text %>
  <%= f.submit 'Submit' %>
<% end %>

app/views/posts/index.html.erb
<h1>All Posts</h1>

<% current_user.posts.each do |pos| %>
  <article class="post">
    <h1><%= pos.title %></h1>
    <ul>
      <li><%= link_to 'Inspect this post', [current_user, pos] %></li>
      <li><%= link_to 'Delete this post', [current_user, pos], method: :delete %></li>
      <li><%= link_to 'Update this post', edit_user_post_path(current_user, pos) %></li>
    </ul>
  </article>
<% end %>

app/views/posts/new.html.erb
<h1>Create a new post</h1>
<%= form_for [current_user, @new_post], method: :post do |f| %>
 <%= f.label :title%>
 <%= f.text_area :title%>
 <%= f.label :text %>
 <%= f.text_area :text %>
 <%= f.submit 'Submit'%>
<% end %>

app/views/posts/show.html.erb
<article class="post-inspect">
  <h1><%= @post.title %></h1>
  <p> <%= @post.text %> </p>
  <%= link_to 'Back to all posts', user_posts_path(current_user)%>
</article>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

app/views/searches/create.html.erb
<h1>Searches#create</h1>
<p>Find me in app/views/searches/create.html.erb</p>

<h1> congratulations! </h1>
<h1> you created a search with the terms <%= @search.search_terms %> </h1>

<% if @search.results %>
  <% @search.posts.each do |pos| %>
    <h1> <%= pos.title %> </h1>
  <% end %>
<% end %>

app/views/searches/destroy.html.erb
<h1>Searches#destroy</h1>
<p>Find me in app/views/searches/destroy.html.erb</p>

app/views/searches/edit.html.erb
<h1>Searches#edit</h1>
<p>Find me in app/views/searches/edit.html.erb</p>

app/views/searches/index.html.erb
<h1>All Searches</h1>

<div class="clear-search"><%= link_to 'clear search history', searches_delete_all_path %></div>

<% @searches.each do |ser| %>
  <article class="search">
    <ul>
      <li> Search ID: <%= ser.id %> </li>
      <li> Search Terms: <%= ser.search_terms %> </li>
      <li> Created At: <%= ser.created_at %> </li>
      <li><%= link_to 'Inspect this search', [current_user, ser] %></li>
    </ul>
  </article>
<% end %>

app/views/searches/new.html.erb
<h1>Create a new search!</h1>



<%= form_for [current_user, @new_search] do |f| %>
 <%= f.label :search_terms%>
 <%= f.text_area :search_terms%>
 <%= f.submit 'Submit'%>
<% end %>

app/views/searches/show.html.erb
<article class="search-inspect">
  <h3> Search ID: <%= @search.id %> </h3>
  <h3> Search terms: <%= @search.search_terms %> </h3>
  <ul>
  <% search = @search.results.sort_by { |m| m.score } %>
  <% search.reverse! %>
  <% search.each do |res| %>
    <li> Title: <%= res.post.title %> </li>
    <li> Text: <%= res.post.text %> </li>
    <br>
  <% end %>
  </ul>
</article>

app/views/searches/update.html.erb
<h1>Searches#update</h1>
<p>Find me in app/views/searches/update.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

<% if current_user %>
 <h1> you are signed in </h1>
<% else %>
  <h1> you are not signed in </h1>
<% end %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/start.html.erb
<h1> Welcome to smart_search </h1> 

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>